language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"

cache:
  directories:
    - elm-stuff/build-artifacts

before_script:
  - bash tests/before_script.sh

script:
  - bash tests/basic_test.sh

notifications:
    email: false

