language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "0.12"
  - "0.10"

before_script:
  - npm install
  - yes | elm-make example/Example.elm --output main.js 
  - node server.js &
  - sleep 2 

script:
  - for i in $(seq 1 10); do curl http://localhost:8080 > "$i.log" ; done
  - sleep 10
  - for i in $(seq 1 10); do grep -Fxq "/$i" "$i.log" || ( echo "File $i.log contains improper data"; cat "$i.log"; ) ; done
notifications:
    email: false
