language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "0.12"
  - "0.10"

before_script:
  - npm install
  - ./run.sh &
  #  - export DISPLAY=:99.0
  #  - sh -e /etc/init.d/xvfb start
  #  - gem update --system
  #  - gem install sass --version ">=3.3.7"
  #  - gem install compass --version ">=0.12.3"
  #  - npm install --quiet -g grunt-cli karma
  #  - npm install
  #  - npm install -g bower
  #  - bower install -f

script:
  - for i in $(seq 1 10000); do curl http://localhost:8080 > out.log & done
notifications:
    email: false
