language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"

cache:
  directories:
    - elm-stuff/build-artifacts

before_script:
  - npm install
  - git clone https://github.com/tunguski/elm-spa-example.git client
  - elm-make --yes example/Example.elm --output main.js
  - node server.js &
  - sleep 2

script:
  - for i in $(seq 1 10); do curl http://localhost:8080 | tee "$i.log" ; done
  - sleep 10
  - for i in $(seq 1 10); do grep -Fxq "/$i" "$i.log" || ( echo "File $i.log contains improper data"; cat "$i.log"; ) ; done
notifications:
    email: false
